Document: libgscgi
Title: Debian libgscgi Manual
Author: <insert document author here>
Abstract: This manual describes what libgscgi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libgscgi/libgscgi.sgml.gz

Format: postscript
Files: /usr/share/doc/libgscgi/libgscgi.ps.gz

Format: text
Files: /usr/share/doc/libgscgi/libgscgi.text.gz

Format: HTML
Index: /usr/share/doc/libgscgi/html/index.html
Files: /usr/share/doc/libgscgi/html/*.html
